#!/usr/bin/env bash
set -euo pipefail

WORKDIR="$HOME/.openclaw/workspace-diabetes/data"
mkdir -p "$WORKDIR"
if [ ! -f "$WORKDIR/README.md" ]; then
  cat > "$WORKDIR/README.md" <<EOF
Data artifacts for Nightscout/Loop reviews.
- Do not share these files; they may contain health data.
- Generated by the assistant on $(date -u).
EOF
fi

NS_BASE="https://emmettk.herokuapp.com"
START_ISO=$(date -u -v -14d "+%Y-%m-%dT%H:%M:%SZ")
END_ISO=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
START_DATE=$(date -u -v -14d +%Y-%m-%d)
START_MS=$(( $(date -u -v -14d +%s) * 1000 ))
START_TAG=$(date -u -v -14d +%Y%m%d)
END_TAG=$(date -u +%Y%m%d)

# Connectivity checks (no data saved)
ENTRIES_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NS_BASE/api/v1/entries/sgv.json?count=1") || true
TREAT_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NS_BASE/api/v1/treatments.json?count=1") || true
PROFILE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NS_BASE/api/v1/profile.json") || true
DEVSTAT_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NS_BASE/api/v1/devicestatus.json?count=1") || true

echo "entries: $ENTRIES_STATUS" > "$WORKDIR/connectivity.txt"
echo "treatments: $TREAT_STATUS" >> "$WORKDIR/connectivity.txt"
echo "profile: $PROFILE_STATUS" >> "$WORKDIR/connectivity.txt"
echo "devicestatus: $DEVSTAT_STATUS" >> "$WORKDIR/connectivity.txt"

# Output files
ENTRIES_OUT="$WORKDIR/ns_entries_${START_TAG}-${END_TAG}.json"
TREAT_OUT="$WORKDIR/ns_treatments_${START_TAG}-${END_TAG}.json"
DEVSTAT_OUT="$WORKDIR/ns_devicestatus_${START_TAG}-${END_TAG}.json"
PROFILE_OUT="$WORKDIR/ns_profile_latest.json"

# Build URLs with percent-encoded query keys
ENTRIES_URL="$NS_BASE/api/v1/entries/sgv.json?find%5Bdate%5D%5B%24gte%5D=$START_MS&count=10000"
TREAT_URL="$NS_BASE/api/v1/treatments.json?find%5Bcreated_at%5D%5B%24gte%5D=$START_DATE&count=10000"
DEVSTAT_URL="$NS_BASE/api/v1/devicestatus.json?find%5Bcreated_at%5D%5B%24gte%5D=$START_DATE&count=10000"

# Fetch data (read-only)
curl -sS "$ENTRIES_URL" -o "$ENTRIES_OUT"
curl -sS "$TREAT_URL" -o "$TREAT_OUT"
# Devicestatus may be public or not; ignore errors
curl -sS "$DEVSTAT_URL" -o "$DEVSTAT_OUT" || true
curl -sS "$NS_BASE/api/v1/profile.json" -o "$PROFILE_OUT"

# Summarize sizes without exposing content
{
  echo "FILES:"
  for f in "$ENTRIES_OUT" "$TREAT_OUT" "$DEVSTAT_OUT" "$PROFILE_OUT"; do
    if [ -f "$f" ]; then
      printf "%s\t%s bytes\n" "$(basename "$f")" "$(wc -c < "$f" | tr -d " ")"
    fi
  done
  echo "CONNECTIVITY"
  echo "entries=$ENTRIES_STATUS"
  echo "treatments=$TREAT_STATUS"
  echo "profile=$PROFILE_STATUS"
  echo "devicestatus=$DEVSTAT_STATUS"
} > "$WORKDIR/summary.txt"

# Print summary path for caller
printf "%s\n" "$WORKDIR/summary.txt"
